WIDTH, HEIGHT = 875, 700
FPS = 60
PLAYER_VEL = 5

BLOCK_SIZE = 96
FLAG_SIZE = 64
FRUIT_SIZE = 32
BOX_WIDTH = 28
BOX_HEIGHT = 24

FRUIT_HEIGHT_OFFSET = HEIGHT - 64
FLAG_HEIGHT_OFFSET = HEIGHT - 128
FIRE_HEIGHT_OFFSET = HEIGHT - 64  
HIDDEN_FRUIT_HEIGHT_OFFSET = HEIGHT - 9
HIDDEN_FRUIT_WIDTH_OFFSET = -5